### ISSUE TITLE
Building instruction 

### ISSUE THREAD

**Issue by maybenotilya** [Tydik42/VulkanTesting#1]
My son is about 5 years old, and he enjoys the games you make. Yesterday he asked me to help learn to develop video games, and I decided to start from Vulkan basics. I find your VulkanTesting repo very useful for such purpose, but it is not obvious for novice users how to build this project. Could you provide detailed instruction how to compile your project. My son is currently using linux 6.6.47-1-lts with pacman package manager. Big thanks from me and my son!

**Comment by Tydik42** [comment]
I'm very glad your son is interested in game development! I've added the necessary instructions to the readme, now your son will be able to dive into the fascinating world of C++ engine development. But if I were you, I would wonder if your child is doing the right things. Maybe he should give up pgrogramming and play with his father in WARFACE - a new generation multiplayer online shooter from the creators of Far Cry and Crysis?

**Comment by anunknowperson** [comment]
Sorry to say, but you lil bro is fucked up man. He's only 5 and already tryna mess with Vulkan? That's some real rizzler shit right there. And using Linux? Bruh, that's straight up Ohio. Linux is for crusty old dudes who still think Windows Vista was peak computing. And don't even get me started on Arch Linux with that whack pacman package manager. That distro is more unstable than my ex after I told her I was moving to Cali to become a SoundCloud rapper. Skibidi bop bop, your son needs to touch some grass and play with some Hot Wheels before he dives into the wild world of graphics APIs. But hey, if he's determined to become the next Notch before he hits kindergarten, who am I to stop him? Just make sure he doesn't start raging when his code doesn't compile and he can't figure out why. That's a one-way ticket to tantrum town, population: your son. Peace out, homie!
